# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smoke}
  s.version = "0.5.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Schwarz"]
  s.date = %q{2009-09-27}
  s.email = %q{ben.schwarz@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "lib/core_ext/hash.rb",
     "lib/core_ext/string.rb",
     "lib/smoke.rb",
     "lib/smoke/cache.rb",
     "lib/smoke/item.rb",
     "lib/smoke/origin.rb",
     "lib/smoke/output/xml.rb",
     "lib/smoke/request.rb",
     "lib/smoke/source/data.rb",
     "lib/smoke/source/feed.rb",
     "lib/smoke/source/join.rb",
     "lib/smoke/source/yql.rb",
     "rdoc/classes/Smoke.html",
     "rdoc/classes/Smoke/Origin.html",
     "rdoc/classes/Smoke/Source/Data.html",
     "rdoc/classes/Smoke/Source/Feed.html",
     "rdoc/classes/Smoke/Source/YQL.html",
     "rdoc/created.rid",
     "rdoc/files/README_markdown.html",
     "rdoc/files/lib/core_ext/hash_rb.html",
     "rdoc/files/lib/smoke/origin_rb.html",
     "rdoc/files/lib/smoke/request_rb.html",
     "rdoc/files/lib/smoke/source/data_rb.html",
     "rdoc/files/lib/smoke/source/feed_rb.html",
     "rdoc/files/lib/smoke/source/join_rb.html",
     "rdoc/files/lib/smoke/source/yql_rb.html",
     "rdoc/files/lib/smoke_rb.html",
     "rdoc/fr_class_index.html",
     "rdoc/fr_file_index.html",
     "rdoc/fr_method_index.html",
     "rdoc/index.html",
     "rdoc/rdoc-style.css",
     "spec/core_ext/hash_spec.rb",
     "spec/smoke/cache_spec.rb",
     "spec/smoke/origin_spec.rb",
     "spec/smoke/output/xml_spec.rb",
     "spec/smoke/request_spec.rb",
     "spec/smoke/shared_spec.rb",
     "spec/smoke/source/data_spec.rb",
     "spec/smoke/source/feed_spec.rb",
     "spec/smoke/source/join_spec.rb",
     "spec/smoke/source/yql_spec.rb",
     "spec/smoke_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/supports/amc_pacer.json.yql",
     "spec/supports/datatables.yql",
     "spec/supports/flickr-photo.json",
     "spec/supports/gzip_response.txt",
     "spec/supports/search-web.json.yql",
     "spec/supports/search-web.xml.yql",
     "spec/supports/slashdot.xml",
     "spec/supports/test_source.rb"
  ]
  s.homepage = %q{http://github.com/benschwarz/smoke}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{smoke is a Ruby based DSL that allows you to query web services such as YQL, RSS / Atom and JSON or XML in an elegant manner.}
  s.test_files = [
    "spec/core_ext/hash_spec.rb",
     "spec/smoke/cache_spec.rb",
     "spec/smoke/origin_spec.rb",
     "spec/smoke/output/xml_spec.rb",
     "spec/smoke/request_spec.rb",
     "spec/smoke/shared_spec.rb",
     "spec/smoke/source/data_spec.rb",
     "spec/smoke/source/feed_spec.rb",
     "spec/smoke/source/join_spec.rb",
     "spec/smoke/source/yql_spec.rb",
     "spec/smoke_spec.rb",
     "spec/spec_helper.rb",
     "spec/supports/test_source.rb",
     "examples/web_search_joined.rb",
     "examples/yql_web_search.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<simple-rss>, ["= 1.2"])
      s.add_runtime_dependency(%q<json>, ["= 1.1.3"])
      s.add_runtime_dependency(%q<fakeweb>, ["= 1.2.5"])
      s.add_runtime_dependency(%q<crack>, ["= 0.1.1"])
      s.add_runtime_dependency(%q<moneta>, ["= 0.6.0"])
      s.add_runtime_dependency(%q<rest-client>, ["= 1.0.3"])
      s.add_runtime_dependency(%q<nokogiri>, ["= 1.3.2"])
    else
      s.add_dependency(%q<simple-rss>, ["= 1.2"])
      s.add_dependency(%q<json>, ["= 1.1.3"])
      s.add_dependency(%q<fakeweb>, ["= 1.2.5"])
      s.add_dependency(%q<crack>, ["= 0.1.1"])
      s.add_dependency(%q<moneta>, ["= 0.6.0"])
      s.add_dependency(%q<rest-client>, ["= 1.0.3"])
      s.add_dependency(%q<nokogiri>, ["= 1.3.2"])
    end
  else
    s.add_dependency(%q<simple-rss>, ["= 1.2"])
    s.add_dependency(%q<json>, ["= 1.1.3"])
    s.add_dependency(%q<fakeweb>, ["= 1.2.5"])
    s.add_dependency(%q<crack>, ["= 0.1.1"])
    s.add_dependency(%q<moneta>, ["= 0.6.0"])
    s.add_dependency(%q<rest-client>, ["= 1.0.3"])
    s.add_dependency(%q<nokogiri>, ["= 1.3.2"])
  end
end
